from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import jwt, JWTError
from sqlmodel import Session, select
from app.database.session import get_session
from app.models.user import User
from app.config.settings import settings
import uuid

# Security scheme for extracting token from Authorization header
security = HTTPBearer()

def verify_better_auth_token(
    credentials: HTTPAuthorizationCredentials = Depends(security),
    session: Session = Depends(get_session)
) -> User:
    """
    Verify Better Auth JWT token and return current user.

    The token is generated by Better Auth on the frontend and includes
    the user ID in the 'sub' claim.

    Raises:
        HTTPException: 401 if token is invalid or user not found
    """
    token = credentials.credentials

    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )

    try:
        # Decode JWT token using the same secret as Better Auth
        payload = jwt.decode(
            token,
            settings.SECRET_KEY,
            algorithms=[settings.ALGORITHM]
        )

        # Extract user_id from 'sub' claim
        user_id_str: str = payload.get("sub")
        if user_id_str is None:
            raise credentials_exception

        # Convert the user ID string to UUID
        try:
            user_id = uuid.UUID(user_id_str)
        except ValueError:
            raise credentials_exception

    except JWTError as e:
        print(f"JWT decode error: {e}")
        raise credentials_exception

    # Get user from database
    statement = select(User).where(User.id == user_id)
    result = session.exec(statement)
    user = result.first()

    if user is None:
        raise credentials_exception

    return user